language: node_js
node_js:
  - "4.4"
branches:
  only: master
addons:
  firefox: "45.7"
before_install:
  - npm install --save selenium-webdriver@2.53.3
  - npm install --save geckodriver
  - npm install --save chai
  - sudo apt-get -qq update
  - sudo apt-get install -y lftp
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install: npm install
cache:
  directories:
    - node_modules
script:
  - "node tests/functional-testing.js"
env:
  global:
    - secure: "qvG8lNnr1vhsfINtaKZKxBcQprHnijhG+MP75q2eTb4GzMudMsUNmUEh6bzSwy+sY27uHqy1fy+1HU5ikyWCDJYK7hLJmBR64DIjagdQ+tIbFGxCesEpvAU6QPjqWDxQPJZ9qiUNmhCCeTAhxSmrqHvzSYOOwSYvPrSfxPBBjkV+vLs9tVFcQ2YCEr4a7NVJF2OuuNEf+eL7wA+rR7lP7FmiMdNPg7cWZB34iKR/FDHiv2N+5pWmAEamUcVkgzR8omOd3Jb/Nzr8+PVkqx/JCybfcNxJqUCdN/SLFdHIpVTee92IAbfSFozPkwGicowPiI6fnGLSKwnw8wB9y6Ca0EKURUqEQaJ4PjJDznLJqliJrZpoedHoCVPYOzHzBrD+w4CKS/SMqXMSn9be44QRSMAL6tc0bA7dxG+GBgYTfWg9zaNY9nHcBsvfeIb4QebYCYTsN8C+VGY/zX45v/qPCE9uakWKJySNI+kEViwaC59p2yNp/tCfNL3vHnn3tayQDXlL/2eq9md2j83n1Oa/HtKVll46RCFpiip5r/FdawuoBuV3sGXmtCVgGs1K5hOqw1kVi11wW3PB8Qtl8dpbroEwZXN1x6/o9scSD5wzgrrhE5HpJUt4Bb0kH68OEvUHRx06FNeCCmvtRD3t4fe0KwuNWWLs6mXdPRZKdI0ezXg="
    - secure: "tX8VnbwomCObCmEHJOYu7jyp2XwxLuyBS+qYYROsYCDGoQTLI13uU9RRrKvKUEJnzRA93dll3QyeOAcFvzovfsdjJ6q8o5zQuCN7MZxaqJ1Ad0Ocg3gjuQdYsUa/Z7ATqBhIQCuOPZ3V6KVkZ5ceWapzmVhpwBNjPs6L7VQfO4HgVcTE2vNMC811+6YHKCOnZj4otu5e2syRFeeq8pD8Er2lS5R7HvDTgmV67hylUy9MAZQdVR2Ykr35GFy8UMngnM9SOBr1qgOzHnPwLiRjaPuninY1fka8FGbGFg0BzgH8epj3i0KbTPKt2VJhw2+vydf3DvkMRTCmglJyG1WRKBNyAGp8Cc0JBUVkckO2LD/vx2peaOerO3QRjANXIBnHfVGwuVwmo5ZtqDa9sIxXzpBM8j+4gIDCaHzwEV34O7wy78sj4huRT9mpNZLvf5dJ5t8MvO1Hb1XNxZT+jHRKqGjRFpLuvDWv1fGP+0ZNFju0/rM8FDE1hqiIlxu2Oi0ohsq02Qt1tWRTSbxv8VQfgQWfK8/LeOsf51Sxs6tPRsq8X3HZGjbfR6CbSF0XmooyWwuof4Kqsq57f3FLhUFQVBeDS9jocGuoc36Y3eo/RSi6KEobsYetQaEGZZH/33ede+HUDzovRjbaKeCcgvkGweBruVjCTVnejBOg+6WoHq4="
after_success:
    "lftp -e 'mirror -R $TRAVIS_BUILD_DIR sp7-geogate-client' -u $FTP_USER,$FTP_PASSWORD sftp://155.253.20.62:4322"